language: cpp
matrix:
  include:
    - dist: bionic
      env:
        # Clang
        - CLANG_VERSION=10
        # CMake
        - BUILD_DIR_PATH=$TRAVIS_BUILD_DIR/build
        - BUILD_TYPE=Debug
        - CMAKE=$HOME/.local/bin/cmake
        - CMAKE_INCLUDE_PATH=$HOME/.local/include
        - CMAKE_LIBRARY_PATH=$HOME/.local/lib
        - CMAKE_PREFIX_PATH=$HOME/.local
        - CMAKE_VERSION=3.16.8
        - CTEST=$HOME/.local/bin/ctest
        # Libraries
        - CATCH2_VERSION=2.13.0
        - CATCH2_URL=https://github.com/catchorg/Catch2/archive/v$CATCH2_VERSION.tar.gz
        - CATCH2_SRC_PATH=$HOME/.local/src/catch2
        - LYRA_VERSION=1.4
        - LYRA_URL=https://github.com/bfgroup/Lyra/archive/$LYRA_VERSION.tar.gz
        - LYRA_SRC_PATH=$HOME/.local/src/lyra
        - SPDLOG_VERSION=1.7.0
        - SPDLOG_URL=https://github.com/gabime/spdlog/archive/v$SPDLOG_VERSION.tar.gz
        - SPDLOG_SRC_PATH=$HOME/.local/src/spdlog
      addons:
        apt:
          update: true
          packages:
            - build-essential
            - clang-10
            - curl
            - llvm-10
            - python3-pip
git:
  submodules: false
before_install:
  # Submodules
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  # Check compilers
  - export CXX=clang++-$CLANG_VERSION
  - export CC=clang-$CLANG_VERSION
  - which $CXX
  - $CXX --version
  - which $CC
  - $CC --version
  # Check LLVM tools
  - which llvm-profdata-$CLANG_VERSION
  - llvm-profdata-$CLANG_VERSION show --version
  - which llvm-cov-$CLANG_VERSION
  - llvm-cov-$CLANG_VERSION show --version
  # Configurations
  - mkdir -p $CMAKE_INCLUDE_PATH
install:
  # Install CMake
  - python3 -m pip install --no-cache-dir --upgrade pip
  - python3 -m pip install --no-cache-dir cmake==$CMAKE_VERSION
  # Install Catch2
  - mkdir -p $CATCH2_SRC_PATH
  - curl -L $CATCH2_URL | tar zx -C $CATCH2_SRC_PATH --strip-components=1
  - cd $CATCH2_SRC_PATH
  - cmake -Bbuild -H. -DBUILD_TESTING=OFF
  - cmake --build build/ --target install
  # Install Lyra
  - mkdir -p $LYRA_SRC_PATH
  - curl -L $LYRA_URL | tar zx -C $LYRA_SRC_PATH --strip-components=1
  - cp -pR $LYRA_SRC_PATH/data/single_include/lyra $CMAKE_INCLUDE_PATH/lyra
  # Install spdlog
  - mkdir -p $SPDLOG_SRC_PATH
  - curl -L $SPDLOG_URL | tar zx -C $SPDLOG_SRC_PATH --strip-components=1
  - cd $SPDLOG_SRC_PATH
  - mkdir build
  - cd build
  - cmake ..
  - make -j
after_install:
  - $CMAKE --version
script:
  # Setup
  - cd $TRAVIS_BUILD_DIR
  - mkdir -p $BUILD_DIR_PATH
  # Run test with address sanitizer
  - ASAN=ON bash script/build.sh
  - bash script/test.sh
  # Run test with code coverage
  - COVERAGE=ON bash script/build.sh
  - bash script/test.sh
after_success:
  # Export coverage data
  - |
    llvm-profdata-$CLANG_VERSION \
      merge $BUILD_DIR_PATH/test/unit/default.profraw \
      -o $TRAVIS_BUILD_DIR/default.profdata
  - |
    llvm-cov-$CLANG_VERSION \
      export $BUILD_DIR_PATH/test/unit/unit_test \
      -instr-profile=$TRAVIS_BUILD_DIR/default.profdata \
      -format=lcov \
      >$TRAVIS_BUILD_DIR/coverage.info
  # Upload coverage data
  - bash <(curl -s https://codecov.io/bash) -f $TRAVIS_BUILD_DIR/coverage.info
notifications:
  slack:
    secure: "sI8yzHpjEUk/M3ZgSnnIToHoSMbIIyJYPJ1pFKbFkPrzl1Zz7mCozEaPZ2cTJji9tLvCgNN0UEKbmmjjA+u+pJsk6q06dOfubm3CIh4ozMOwFR1qjYHmOYlxjGD2OiDttylMwV/0i3xo1dWoo4+mAaghm/85KByU5eVOVeO5pLappVwCRVGlCmgLIGuGqKNayI0/TwcOrVA8Ep+rv+SKmy3GLV0uJfztcu/UMvBlqyHjD0E64uCt5U7OkvdG3BPE0KBsMhy0T6OrULFkCQF2lA1eFns4PPD8zP3dc8h2fmK8DEzsKXZazyMtNad3YC0lPphPZ4Jz/ZFeCxIHMVqtHZnwzWZzp4aDW2mZnZ//C85pG6EC3VGArcYo2Rc1ZB4lTSWN68W0NZTV6phVjqF2P082bA78FpDmCjfxQI60eHlygTwT2sffjMp+h9TaL0BwYUw6TbjZIh/6hGiNVfmpsZ6aZz7t2Xf/wOvtIcIqLDf7Tbr5pNlylpZRpQZexZgoIG++V0zS8NEUvvUuwp2ois9E/E24GMrc8CejOM3VokIAEIuwtoKkDQyMSXrqc5BpZioB9DczJ0yG14IDk+Ol7T/MNho9UOX2ro4rg6CxxRWpUmUy/OXrHmTJX3l+nzu6Y7kjwn0SrHzku9F0khFl7n0HZiMFdyngNrwSI2Axg9M="
